
import './globals.css'



export const metadata = {
  title: 'ইজি লার্নিং প্লাটফর্ম',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
