
import './globals.css'



export const metadata = {
  title: 'Learning Platform',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body>{children}</body>
    </html>
  )
}
