'use client'

import DashNavbar from "@/components/dashboard/DashNavbar";
import UserSidebar from "@/components/dashboard/userDashboard/UserSidebar";
import UserWelcome from "@/components/dashboard/userDashboard/UserWelcome";
import { isLoggedIn } from "@/services/auth.service";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";


// export const metadata = {
//   title: 'ড্যাশবোর্ড',
//   description: 'Generated by create next app',
// }
const DashBoardLayout = ({children}) => {
  const router = useRouter();
  const userLoggedIn = isLoggedIn();
  const [isLoading, setIsLoading] = useState(false);

  useEffect(()=>{
    if(!userLoggedIn){
      router.push("/login")
    }
    setIsLoading(true)
  },[]);

  if(!isLoading){
    return <p>Loading.................</p>
  }


  return (
    <>
       <div className="">
        <DashNavbar/>
        <div className=" grid grid-cols-2  bg-gray-200">
            <div className="bg-white  h-screen w-60 mt-5 border border-gray-300 rounded ml-5 ">
                <UserSidebar/>
            </div>
            <div className="bg-white  w-100 mt-5 rounded px-10 pt-10 mr-10" style={{marginLeft:'-300px'}}>
            <UserWelcome/>
            <br />
            {children}
            
            </div>
        </div>
        

        
    </div>
    </>
  )
}




export default DashBoardLayout;








