'use client'

import DashNavbar from "@/components/dashboard/DashNavbar";
import UserSidebar from "@/components/dashboard/userDashboard/UserSidebar";
import UserWelcome from "@/components/dashboard/userDashboard/UserWelcome";
import { useGetSingleUserQuery } from "@/redux/api/authApi";
import { getUserInfo, isLoggedIn } from "@/services/auth.service";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";


// export const metadata = {
//   title: 'ড্যাশবোর্ড',
//   description: 'Generated by create next app',
// }
const DashBoardLayout = ({ children }) => {
  const router = useRouter();
  const userLoggedIn = isLoggedIn();
  const [isLoading, setIsLoading] = useState(false);
  const { role, userId } = getUserInfo();


  const { data: user } = useGetSingleUserQuery(userId);

  useEffect(() => {
    // if(role !== 'admin' || role !== 'super_admin'){
    //   router.push('/')
    // }
    if (!userLoggedIn) {
      router.push("/login")
    }
    setIsLoading(true)
  }, [router, isLoading, userLoggedIn]);

  if (!isLoading) {
    return <p className="text-center py-20 text-2xl font-bold">Loading.................</p>
  }




  return (
    <>
      <div className="">
        <DashNavbar />
        <div className=" grid  lg:grid-cols-2  bg-gray-200">
          <div className="bg-white  mt-5 border border-gray-300 rounded ml-5 ">
            <UserSidebar />
          </div>
          <div className="bg-white   mt-5 rounded px-10 pt-10 lg:mr-10 lg:ml-[-300px]" >
            <UserWelcome />
            <br />
            {children}

          </div>
        </div>



      </div>
    </>
  )
}




export default DashBoardLayout;








